### ISSUE TITLE
Pandas warning

### ISSUE THREAD

**Issue by ilcardella** [ilcardella/TradingBot#11]
https://github.com/ilcardella/TradingBot/blob/b566898244930bf911da741f51b986c622cbc1d6/scripts/Strategies/SimpleMACD.py#L112

This line triggers a warning from Pandas package:
```SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  px['positions'][9:]=np.where(px['macd'][9:]>=px['macd_signal'][9:],1,0)```

Requires investigation

**Comment by andrebask** [comment]
@ilcardella I think the slice creates a new list object, and then you are assigning a value to it, so that doesn't change the original matrix?

**Comment by ilcardella** [comment]
So could we use a buffer to save the output of the where() and then assign the DataFrame with the buffer?

**Comment by ilcardella** [comment]
has been merged
