### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-66ey9v1k/

### ISSUE THREAD

**Issue by mgzlp** [ilcardella/TradingBot#278]
Hi, when trying to run "make install-system", I keep getting following output/error:

```
rm -rf *egg-info
rm -rf build/
rm -rf dist/
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f  {} +
find . -name '__pycache__' -exec rm -rf  {} +
find . -name '_build' -exec rm -rf  {} +
find . -name '.mypy_cache' -exec rm -rf  {} +
find . -name '.pytest_cache' -exec rm -rf  {} +
python3 -m pip install --user .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /home/pi/TradingBot/TradingBot
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-66ey9v1k/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-66ey9v1k/
make: *** [Makefile:29: install-system] Error 1
```

I'm on Linux. Can someone help?

**Comment by ilcardella** [comment]
from your log it seems you are running on a raspberry pi, is that correct? What version is it? Is it the latest based on arm64?

**Comment by mgzlp** [comment]
Yes, it is the latest one.

**Comment by ilcardella** [comment]
Unfortunately I do not have a raspberry Pi so I can't try to replicate your issue.
Are you using the latest version of `pip`? If not it might worth upgrading it and try again. Also what version of Python do you have installed?
On a side note, there is also a Docker image for arm64: `docker pull ilcardella/tradingbot:latest-arm`

**Comment by mgzlp** [comment]
I doubled-checked, everything is on the newest version. I also tried the Docker image, but also don't seem to work :(

I downloaded the setup.py from one of the older versions of this project (had to modify it a bit), which took me a bit further. I was able do execute `make install-system` and can run `trading_bot` now. 

Now I'm running into another problem when executing `trading_bot`:
```
Traceback (most recent call last):
  File "/home/pi/.local/bin/trading_bot", line 6, in <module>
    from TradingBot import main
ModuleNotFoundError: No module named 'TradingBot"
```

My (custom) setup.py:
```
from setuptools import setup, find_namespace_packages
import os

setup(
    name="TradingBot",
    version="2.0.0",
    python_requires='>=3',

    package_dir={'': 'tradingbot'},
    packages=find_namespace_packages(where='tradingbot'),
    scripts=['tradingbot/trading_bot.py'],
    entry_points={
        'console_scripts': [
            'trading_bot = TradingBot:main'
        ],
    },

    install_requires=[
        'alpha-vantage==2.1.2',
        'certifi==2019.9.11',
        'chardet==3.0.4',
        'govuk-bank-holidays==0.5',
        'idna==2.8',
        'numpy==1.17.4',
        'panda==0.3.1',
        'pandas==0.25.2',
        'python-dateutil==2.8.1',
        'pytz==2019.3',
        'requests==2.22.0',
        'scipy==1.3.2',
        'six==1.13.0',
        'urllib3==1.25.7',
    ],

    package_data={
        'config': ['*.json']
    },
    data_files=[
        (os.path.join(os.path.expanduser('~'), '.TradingBot', 'config'), ['config/config.json'])
    ],

    # metadata to display on PyPI
    author="Alberto Cardellini",
    author_email="",
    description="Autonomous market trading script",
    keywords="trading stocks finance",
    url="https://github.com/ilcardella/TradingBot",
    project_urls={
        "Bug Tracker": "https://github.com/ilcardella/TradingBot/issues",
        "Documentation": "https://tradingbot.readthedocs.io",
        "Source Code": "https://github.com/ilcardella/TradingBot",
    },
    classifiers=[
        'License :: OSI Approved :: MIT License'
    ]
)
```

Maybe you can help me with that?
If you need the trading_bot or trading_bot.py from /home/pi/.local/bin/ please let me know.

**Comment by ilcardella** [comment]
Just for reference for the future could you confirm what version of Python and `pip` you are using? Maybe also post a `pip freeze`. I wonder if there is some other package that pip requires in order to install, maybe `setuptools`, not sure.
What is the problem you are having with the Docker image instead?

Regarding your "workaround" the problem you are describing seems due to the `entry_point` referring to `TradingBot` instead of `tradingbot`.
Even if I am not suggesting this approach (I'd rather investigate the issue), you could generate the `setup.py` using `poetry`:
```
$ poetry build
$ tar -xvf dist/*.tar.gz --wildcards --no-anchored '*/setup.py' --strip=1
```

**Comment by mgzlp** [comment]
I'm getting back to this as quickly as possible.
Right now I'm on a journey, so I can't access my Raspberry Pi..
